### ISSUE TITLE
Error in ACTIONet:::.preprocess_marker_labels

### ISSUE THREAD

**Issue by pstrybol** [shmohammadi86/ACTIONet#12]
Hi,

When trying to annotate cell types using markers I get the following error:
`Error in ACTIONet:::.preprocess_marker_labels(markers, rownames(S)) : 
  object 'markers' not found`

My command:
`annot.out = annotate.cells.using.markers(ace = ACTIONet.out, markers = marker.genes, thread_no = 12)`

It seems that the preprocessing function can't find the markers object even though it is a required argument. Also, when I leave out the `markers` argument I get the same error instead of an error pointing to a missing argument with no default (like with `ace`).

What could be the problem here?

Kind regards

**Comment by sebastianpineda** [comment]
We actually caught and fixed this a few days ago. The fix has been applied in the "R-devel" branch, which should be stable.

**Comment by pstrybol** [comment]
Thanks for the quick reply. I installed the "R-release:" version using devtools, is it possible to install the "R-devel" branch like so:
`devtools::install_github("shmohammadi86/ACTIONet", ref = "R-devel")`

Or do I need to install from the repo? And do I need to uninstall the current version of ACTIONet?

**Comment by shmohammadi86** [comment]
Yes, you can directly install it by changing the ref as you did. No need to
do anything else (except restarting your R session after, of course)
