### ISSUE TITLE
Detailed documentation required

### ISSUE THREAD

**Issue by pstrybol** [shmohammadi86/ACTIONet#13]
I am getting to know the package and I find the potential is very high for these kind of packages. I would like to use it in combination with SCINET. However, there is some contradicting information between the docs of [ACTION](http://compbio.mit.edu/ACTIONet/tutorials/guide.html#running-actionet) and the demo's situated in the [SCINET repo](https://github.com/shmohammadi86/SCINET/blob/master/demo/Run_ACTIONet_PBMC.Rmd). In general I had the following question: 

1.  Are the `ace$S_r` and `ace$ACTION` attribute the same? Do they represent the ACTION similarity metric/kernel? 
2. Why does `ace$ACTION` have a dim of n_cells x reduced_dim instead of n_cells x n_cells like the `ace$ACTIONet`? 
3. What is the difference between the attributes `Enrichment` and `Confidence` after annotating the archetypes?
4. In the [ACTION docs](http://compbio.mit.edu/ACTIONet/tutorials/guide.html#running-actionet), unreliable archetypes are pruned and unified manually while this seems to be done automatically in the [SCINET demo](https://github.com/shmohammadi86/SCINET/blob/master/demo/Run_ACTIONet_PBMC.Rmd)? Was this an update and is this now always done automatically?
5. There is no `ace$trace` attribute
6. I can't find the function `update.Labels`
7. From the ACTION docs it seems that you need the build the ACTION graph yourself with `build_ACTIONet` and then store is under `ace$ACTIONet`, but by default after running ACTIONet there is already an attribute containing a matrix of n_cells x n_cells which I assume holds cell similarity values between 0 and 1?
8. In the SCINET demo they use a function `plot.ACTIONet.igraph` but I can't find that function. Has it been deprecated in favor of `plot.ACTIONet`?
9. Is there a way to specify upfront how many archetypes you want?

I realize this is a lot to ask for but I would greatly appreciate of you could help me this!

Thanks a lot!

**Comment by shmohammadi86** [comment]
Thanks a lot for the thoughtful questions. Please find responses below:

On Wed, Apr 14, 2021 at 5:39 AM Pieter-Paul Strybol <
***@***.***> wrote:

> I am getting to know the package and I find the potential is very high for
> these kind of packages. I would like to use it in combination with SCINET.
> However, there is some contradicting information between the docs of
> ACTION
> <http://compbio.mit.edu/ACTIONet/tutorials/guide.html#running-actionet>
> and the demo's situated in the SCINET repo
> <https://github.com/shmohammadi86/SCINET/blob/master/demo/Run_ACTIONet_PBMC.Rmd>.
> In general I had the following question:
>
>    1. Are the ace$S_r and ace$ACTION attribute the same? Do they
>    represent the ACTION similarity metric/kernel?
>
> They are the same. ace$ACTION %*% Matrix::t(ace$ACTION) mimics the kernel
as provided in the original paper.

>
>    1. Why does ace$ACTION have a dim of n_cells x reduced_dim instead of
>    n_cells x n_cells like the ace$ACTIONet?
>
> They are the same

>
>    1. What is the difference between the attributes Enrichment and
>    Confidence after annotating the archetypes?
>
> Confidence is the maximum value of Enrichment per annotation class (is a
vectorized form of it)

>
>    1. In the ACTION docs
>    <http://compbio.mit.edu/ACTIONet/tutorials/guide.html#running-actionet>,
>    unreliable archetypes are pruned and unified manually while this seems to
>    be done automatically in the SCINET demo
>    <https://github.com/shmohammadi86/SCINET/blob/master/demo/Run_ACTIONet_PBMC.Rmd>?
>    Was this an update and is this now always done automatically?
>
> run.ACTIONet() now does internally call the pruning function which
automatically removes unreliable archetypes

>
>    1. There is no ace$trace attribute
>
> That is for the older versions of ACTIONet.

>
>    1. I can't find the function update.Labels
>
> Again, an old function. We need to update the docs. Now it
is correct.cell.annotations()

>
>    1. From the ACTION docs it seems that you need the build the ACTION
>    graph yourself with build_ACTIONet and then store is under ace$ACTIONet,
>    but by default after running ACTIONet there is already an attribute
>    containing a matrix of n_cells x n_cells which I assume holds cell
>    similarity values between 0 and 1?
>
> Yes, that is true. ace$ACTIONet is the cell-cell similarity matrix with
values always between [0, 1].

>
>    1. In the SCINET demo they use a function plot.ACTIONet.igraph but I
>    can't find that function. Has it been deprecated in favor of
>    plot.ACTIONet?
>    2. Is there a way to specify upfront how many archetypes you want?
>
> The easiest way to interface with SCINET is to use
the run.SCINET.archetype() function. It is slightly different that the
original paper, but it builds a list of archetype-specific networks.

>
>
> I realize this is a lot to ask for but I would greatly appreciate of you
> could help me this!
>
Don't hesitate to ask any further questions.

**Comment by pstrybol** [comment]
Thanks a lot for the answers!

**Comment by pstrybol** [comment]
Hi, 

I wanted to run the function ` run.SCINET.archetype()` as you suggested but it failed halfway through because of the following error:
`"Post-processing networks\n"`
`Error in V(G): could not find function "V"`

Do you know what the problem might be?

Thanks!

**Comment by shmohammadi86** [comment]
Run require(igraph) first
