### ISSUE TITLE
Install error (cholmod.h not found; macOS)

### ISSUE THREAD

**Issue by dpcook** [shmohammadi86/ACTIONet#27]
Hi there,

Sorry to drop another install error into the issues here. If there is no obvious issue, I can close the issue, but I figured I would include this because it's a fresh macOS installation.

macOS Monterey
MacBook Pro (Apple M1 Max) - fresh OS install
1) Installed command line tools
2) homebrew (with /opt/homebrew/bin added to $PATH)
3) `brew install hdf5 suite-sparse` 
3) installed gfortran
4) R 4.1.2 (x86 via Rosetta)
5) Tried to install actionet

```
devtools::install_github("shmohammadi86/ACTIONet", ref = "R-release")
```

```
Downloading GitHub repo shmohammadi86/ACTIONet@R-release
✓  checking for file ‘/private/var/folders/v3/bfqywp6s08ddpjwj8ynyfmjw0000gn/T/Rtmp1KeRJk/remotes1f397a719e0e/shmohammadi86-ACTIONet-36b7b63/DESCRIPTION’ ...
─  preparing ‘ACTIONet’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘ACTIONet_2.1.9.tar.gz’ (1.7s)
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘ACTIONet/inst/include/ACTIONet/nmslib/similarity_search/include/factory/method/pivot_neighb_invindx.h’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘ACTIONet/inst/include/ACTIONet/nmslib/similarity_search/include/factory/method/simple_inverted_index.h’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘ACTIONet/inst/include/ACTIONet/nmslib/similarity_search/include/factory/space/space_sparse_dense_fusion.h’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘ACTIONet/inst/include/ACTIONet/nmslib/similarity_search/include/method/hnsw_distfunc_opt_impl_inline.h’
   
* installing *source* package ‘ACTIONet’ ...
** using staged installation
** libs
Using Mac OS configurations
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG `find ../inst/include -type d -print | sed s/^/-I/` -w -m64 -DINT_64BITS -DARMA_64BIT_WORD -O2 -march=native -mtune=native -w -m64 -fno-strict-aliasing -fomit-frame-pointer -funroll-loops -fexpensive-optimizations -I/usr/local/opt/suite-sparse/include -DACCELERATE -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppArmadillo/include' -I/usr/local/include  `find ../inst/include -type d -print | sed s/^/-I/` -w -m64 -DINT_64BITS -DARMA_64BIT_WORD -O2 -march=native -mtune=native -w -std=c++14 -m64 -fno-strict-aliasing -fomit-frame-pointer -funroll-loops -fexpensive-optimizations -fPIC  -Wall -g -O2  -c ACTIONet.cpp -o ACTIONet.o
```
etc

And then the header error
```
In file included from ACTIONet/misc/my_utils.cc:1:
In file included from ../inst/include/ACTIONet.h:29:
../inst/include/ACTIONet/my_utils.h:5:10: fatal error: 'cholmod.h' file not found
#include "cholmod.h"
         ^~~~~~~~~~~
1 error generated.
make: *** [ACTIONet/misc/my_utils.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ACTIONet/decomposition/coreset.cc:1:
In file included from ../inst/include/ACTIONet.h:29:
../inst/include/ACTIONet/my_utils.h:5:10: fatal error: 'cholmod.h' file not found
#include "cholmod.h"
         ^~~~~~~~~~~
```

cholmod.h is in `/opt/homebrew/Cellar/suite-sparse/5.10.1_1/include` but doesn't seem to be seen.

Do you have any idea what could cause this? Thanks!

**Comment by sebastianpineda** [comment]
Interesting. Unlike for the Linux version, the brew install location of sparse-suite is actually hardcoded in the RCpp Makefile because it has been static for years. Looks like either a new Brew version or macOS 12 caused this to no longer be the case. If this is the only issue it should be trivial to fix by having it just search properly for the library. The current implementation is kinda lazy anyway. I'll try to get to it this weekend and push a fix to both release and devel. Thanks for bringing this up.

If you'd rather not wait you can just change the location of the suite-sparse directory [here](https://github.com/shmohammadi86/ACTIONet/blob/R-release/src/Makevars#L26-L27) and try installing again.

**Comment by sebastianpineda** [comment]
Alright, I think we fixed it. Take a look. It builds on our machines, but we don't have any M1's.

**Comment by dpcook** [comment]
Hi @sebastianpineda--thanks for looking into this. Ir really appreciate it.

This definitely seems related to some current weirdness with x86/Rosetta R and Arm homebrew (changing default installation to /opt/homebrew). I've found various posts about the toolchain being messed up along with suggestions to modify the compiler setup to get around it. I also suspect the arm/x86 combinations are creating some compatibility issues (see error below--not my expertise at all)

With your change, it now finds the directory with `cholmod.h`, although provides a warning about x86/arm and later throws an error about unable to load shared object from a lock directory

```
#typical clang out output
ld: warning: ignoring file /opt/homebrew/Cellar/suite-sparse/5.10.1_1/lib/libcholmod.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
installing to /Library/Frameworks/R.framework/Versions/4.1/Resources/library/00LOCK-ACTIONet/00new/ACTIONet/libs
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Warning: replacing previous import ‘ggplot2::last_plot’ by ‘plotly::last_plot’ when loading ‘ACTIONet’
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Warning: replacing previous import ‘ggplot2::last_plot’ by ‘plotly::last_plot’ when loading ‘ACTIONet’
Error: package or namespace load failed for ‘ACTIONet’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/00LOCK-ACTIONet/00new/ACTIONet/libs/ACTIONet.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.1/Resources/library/00LOCK-ACTIONet/00new/ACTIONet/libs/ACTIONet.so, 0x0006): symbol not found in flat namespace '_cholmod_allocate_triplet'
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/ACTIONet’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/62/7_ssbt9j7gz179s2hz9hsx2w0000gn/T//RtmpSwuLVG/fileb9ff3577b429/ACTIONet_2.1.9.tar.gz’ had non-zero exit status
```

If this is just something weird due to the processors, feel free to close this and I can shelf it until native arm support is a bit more solidified.

**Comment by sebastianpineda** [comment]
Yeah, it looks like it could be a cross-compilation issue. Nothing in our code should be architecture specific (I don't think, but @shmohammadi86 would know better), but some of the dependencies could very well be. Looks like suite-sparse may be one of those. Unfortunately we don't have any ARM machines to test on and if it is dependency related, we won't be able to do much until those packages get ARM support. Sorry about that.
