### ISSUE TITLE
R package loading/linking error

### ISSUE THREAD

**Issue by najoshi** [shmohammadi86/ACTIONet#29]
I am trying to install the ACTIONet R package on an Ubuntu 16.04 system (that is the version of the computers on our cluster). I have to use a newer version of gcc than the one standard for 16.04, so I am using an install of gcc 8.2.0. Basically, when trying to load the ACTIONet.so file, it looks for the libstdc++ library. However, the library file that it finds is the wrong one.... it needs to find the one associated with the install of gcc 8.2.0, NOT the default one. I have set all of the environment variables I can think of, such as LD_LIBRARY_PATH, LIBRARY_PATH, C_INCLUDE_PATH, etc. to point to the correct directory (/software/gcc/8.2.0/lssc0-linux/lib64), and yet I am still getting the problem below. I have also tried adding the path as a "-L" option in the Makevars file, but still the same error.

So for the testing of loading from the temp location... does that somehow not get the correct path? Any help would be highly appreciated.

** testing if installed package can be loaded from temporary location
Warning: replacing previous import 'ggplot2::last_plot' by 'plotly::last_plot' when loading 'ACTIONet'
Error: package or namespace load failed for 'ACTIONet' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/share/biocore/joshi/sandbox/actionet/00LOCK-ACTIONet/00new/ACTIONet/libs/ACTIONet.so':
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /share/biocore/joshi/sandbox/actionet/00LOCK-ACTIONet/00new/ACTIONet/libs/ACTIONet.so)
Error: loading failed
Execution halted
ERROR: loading failed
\* removing '/share/biocore/joshi/sandbox/actionet/ACTIONet'

**Comment by shmohammadi86** [comment]
Hi,

Thanks for your message. Maybe this post helps:
https://stackoverflow.com/questions/16992628/path-to-libstdc-while-installing-r-package

**Comment by najoshi** [comment]
Yes, that worked. I did not know about the R_LD_LIBRARY_PATH environment variable. Thank you!
