### ISSUE TITLE
Annotation using markers

### ISSUE THREAD

**Issue by Lioscro** [shmohammadi86/ACTIONet#4]
For both `annotate.archetypes.using.markers` and `annotate.cells.using.markers`, a list of lists of genes are provided, each list specifying gene markers for a cell type.

When there aren't cell names assigned to the lists, we give them generic `Celltype %s` names, where `%s` is 1...# of cells.
I don't think these names are applied to the marker genes list at all.
https://github.com/shmohammadi86/ACTIONet/blob/R-devel/R/annotation.R#L101
https://github.com/shmohammadi86/ACTIONet/blob/R-devel/R/annotation.R#L210

Therefore, when creating the `markers.table`, `names(marker.genes) == NULL` and the `markers.table` is empty.
Not familiar with R conventions of doing this, so posting an issue instead.

**Comment by shmohammadi86** [comment]
Not sure what is the issue exactly, since both of those functions
work/should work fine. Annotation is typically a named numeric vector.
Before saving it to AnnData it is being cast back as a factor/ordinal.

**Comment by Lioscro** [comment]
When I run it I get
```
Error in if (dim(markers.table)[1] == 0) { : argument is of length zero
```
Possibly because when creating `markers.table`, `names(marker.genes)` is used instead of `GS.names`

**Comment by shmohammadi86** [comment]
Can you provide the exact code you run? Thanks.

**Comment by Lioscro** [comment]
```
annotate.archetypes.using.markers(ace, list(list('AL669831.5+', 'LINC00115+'), list('FAM41C+', 'NOC2L+')))
```
These are just two random genes.

**Comment by shmohammadi86** [comment]
Use::

list(C1 = c('AL669831.5+', 'LINC00115+'), C2 =c('FAM41C+', 'NOC2L+')))

**Comment by Lioscro** [comment]
Looks like `GS.names` is assigned but never used?

**Comment by shmohammadi86** [comment]
Addressed
