### ISSUE TITLE
specify additional ACTIONet R deps in README

### ISSUE THREAD

**Issue by annashch-insitro** [shmohammadi86/ACTIONet#9]
R CMD INSTALL .
* installing to library ‘/opt/anaconda3/envs/sc_tutorial/lib/R/library’
ERROR: dependencies ‘ineq’, ‘rmdformats’, ‘pals’, ‘seriation’, ‘networkD3’, ‘metap’ are not available for package ‘ACTIONet’

Just confirming that these should be added to readme as deps?

**Comment by shmohammadi86** [comment]
Yes, I think they should all be in the DESCRIPTION file now

**Comment by annashch-insitro** [comment]
great, thanks!
